### ISSUE TITLE
concurrently write to the same database file 

### ISSUE THREAD

**Issue by JaSei** [Grinnz/Minion-Backend-SQLite#7]
Hi,
I try [minion benchmark](https://metacpan.org/source/SRI/Minion-6.0/examples/minion_bench.pl) with sqlite and if is more workers then 1, then benchmark failed:

```
Clean start with 10000 jobs
Enqueued 10000 jobs in 1.95973110198975 seconds (5102.741/s)
7764 has started 2 workers
7765 will finish 1000 jobs
7766 will finish 1000 jobs
DBD::SQLite::st execute failed: database disk image is malformed at /home/seidl/.carmel/5.22.2-x86_64-linux-thread-multi/builds/Mojo-SQLite-1.000/blib/lib/Mojo/SQLite/Database.pm line 105.
```

problem is in concurrent write to DB, which SQLite support, but only one can write at a time.

Will by possible create some semaphore mechanism for writing to DB (via DB)? Performance will be maybe decrease, but db-file don't corrupted.

my idea is something like - before insert/update look to semaphore and waiting if is used... if is released, then next worker lock and write (ideal in transaction)...

**Comment by Grinnz** [comment]
The minion benchmark script works if you disconnect the database handle after enqueueing jobs and before forking. I am not sure why. I can include this modified example script in the distribution in the future.

**Comment by Grinnz** [comment]
The modified example script is here: https://github.com/Grinnz/Minion-Backend-SQLite/blob/master/examples/minion_bench.pl

As you can see, concurrent writes work fine due to setting WAL mode in Mojo::SQLite. I have not been able to determine the cause of the database corruption if the connection is opened before forking, but the problem doesn't seem to occur in normal Minion use. Please reopen the issue if you encounter further problems.

**Comment by JaSei** [comment]
Thank you. Now works good and pretty fast;)
